### PR TITLE
StateDB using IPFS-backed trie and supporting types

### PR DESCRIPTION
**Pull request by roysc**
This read-only implementation of `StateDB` is compatible with v5 [ipfs-ethdb](https://github.com/cerc-io/ipfs-ethdb) and can be used for benchmarking that access pattern.

Yet to be done is adding iterator and proof capabilities, and adding tests.

Implements https://github.com/cerc-io/ipld-eth-statedb/issues/13 and https://github.com/cerc-io/ipld-eth-utils/issues/2.

### CODE REVIEW

**Review by i-norden — COMMENTED** [review]
This looks great!

One question: don't see ipfs-ethdb being imported and used here, it looks like you have reimplemented some of that functionality internally here? Is the plan to remain like this, or to use the v5 ipfs-ethdb once a release is cut? Will it be required for the iterator and proof support?

As you know we need the iterator and proof support (unless I am misunderstanding, and this can be used for  supporting `eth_proof` without exposing the `GetProof` interface at this level?) and tests before we can consider this done, but I would be fine with merging this in and doing those in separate PR to keep things less busy.

**Comment by roysc** [comment]
> One question: don't see ipfs-ethdb being imported and used here, it looks like you have reimplemented some of that functionality internally here? Is the plan to remain like this, or to use the v5 ipfs-ethdb once a release is cut? Will it be required for the iterator and proof support?

This doesn't actually need to import the code, since it only reads through an `ethdb.Database` interface. That said, we may want to use it to insert data for tests, but since we want to consolidate that repo into this one anyway, we can add such tests once that's done.

> As you know we need the iterator and proof support (unless I am misunderstanding, and this can be used for supporting `eth_proof` without exposing the `GetProof` interface at this level?) and tests before we can consider this done, but I would be fine with merging this in and doing those in separate PR to keep things less busy.

Right, this PR is just enough to run the benchmarks. Proof and iterator support don't seem like too much of a lift though, so I'll take a crack at them now.

**Comment by i-norden** [comment]
Thanks for reminding me the first purpose of this (benchmarks), that makes sense. If this doesn't need to use ipfs-ethdb (and won't need it for iterator and proof support; which it looks like it won't) then I don't know that we'll need to use and maintain ipfs-ethdb at all anymore.

**Comment by i-norden** [comment]
The benchmarks in https://github.com/cerc-io/eth-statedb-benchmark are also a test/demonstration of this work, so I'd be fine with merging this if you'd prefer to break the remaining work up across separate PRs

**Comment by i-norden** [comment]
We also need the iterator functionality for https://github.com/cerc-io/eth-ipfs-state-validator

**Comment by i-norden** [comment]
Merging this and then moving it to ipld-eth-statedb, thanks!

**Pull request merged**
